<br><br><img src="images/Aide/Singleton nu.png"><br><br>
<br><br><img src="images/Aide/solo.png"><br><br>
<br><br><img src="images/Aide/jumeaux.png"><br><br>
<br><br><img src="images/Aide/Duo.png"><br><br>
<br><br><img src="images/Aide/Trio.png"><br><br>
<br><br><img src="images/Aide/Triples.png"><br><br>
<br><br><img src="images/Aide/Quadruples.png"><br><br>
<br><br><img src="images/Aide/Jumeaux isolés.png"><br><br>
<br><br><img src="images/Aide/Triples isolés.png"><br><br>
<br><br><img src="images/Aide/Gratte ciel.png"><br><br>
<br><br><img src="images/Aide/Remote pair-1.png"><br><br>
<br><br><img src="images/Aide/turbot fish.png"><br><br>
<br><br><img src="images/Aide/sue de coq.png"><br><br>
<br><br><img src="images/Aide/sue decoq exemple.png"><br><br>
<br><br><img src="images/Aide/Cerf volant.png"><br><br>
<br><br><img src="images/Aide/w wing.png"><br><br>
<br><br><img src="images/Aide/rectangle vide.png"><br><br>
<br><br><img src="images/Aide/X-Chain (Color Trap).png"><br><br>
<br><br><img src="images/Aide/X-Chain Color Cycle).png"><br><br>
<br><br><img src="images/Aide/XY-Wing.png"><br><br>
<br><br><img src="images/Aide/L'attaque du cobra explication.png"><br><br>
<br><br><img src="images/Aide/L'attaque du cobra.png"><br><br>
<br><br><img src="images/Aide/swordfish vertical.png"><br><br>
<br><br><img src="images/Aide/swordfih horizontal.png"><br><br>
<br><br><img src="images/Aide/Forteresse maxilien.png"><br><br>
<br><br><img src="images/Aide/Franken X-Wing.png"><br><br>
<br><br><img src="images/Aide/sashimi double finned xwing.png"><br><br>
<br><br><img src="images/Aide/XY-Chain (la griffe du tigre).png"><br><br>
<br><br><img src="images/Aide/XY-Chain (la griffe du tigre) Exemple.png"><br><br>
<br><br><img src="images/Aide/XY-Chain bis.png"><br><br>
<br><br><img src="images/Aide/XY-Chain next.png"><br><br>
<br><br><img src="images/Aide/AIC Type I.png"><br><br>
<br><br><img src="images/Aide/AIC Type I.png bis"><br><br>
<br><br><img src="images/Aide/AIC Type I exemple.png"><br><br>
<br><br><img src="images/Aide/AIC Type I exemple bis.png"><br><br>
<br><br><img src="images/Aide/AIC Type I exemple1.png"><br><br>
<br><br><img src="images/Aide/AIC Type I exemple1 bis.png"><br><br>
<br><br><img src="images/Aide/AIC Type I exemple2.png"><br><br>
<br><br><img src="images/Aide/AIC Type I exemple3.png"><br><br>
<br><br><img src="images/Aide/AIC Type II.png"><br><br>
<br><br><img src="images/Aide/AIC Type II bis.png"><br><br>
<br><br><img src="images/Aide/AIC Type II Exemple.png"><br><br>
<br><br><img src="images/Aide/AIC loop continue.png"><br><br>
<br><br><img src="images/Aide/AIC loop continue Exemple.png"><br><br>
<br><br><img src="images/Aide/AIC loop continue Exemple bis.png"><br><br>
<br><br><img src="images/Aide/AIC loop continue Exemple2.png"><br><br>
<br><br><img src="images/Aide/AIC loop continue Exemple2 bis.png"><br><br>
<br><br><img src="images/Aide/AIC loop discontinu.png"><br><br>
<br><br><img src="images/Aide/AIC loop discontinu bis.png"><br><br>
<br><br><img src="images/Aide/AIC loop discontinu Exemple.png"><br><br>
<br><br><img src="images/Aide/AIC loop discontinu Exemple bis.png"><br><br>
<br><br><img src="images/Aide/death blossom.png"><br><br>
<br><br><img src="images/Aide/ALS-XY-WING.png"><br><br>
<br><br><img src="images/Aide/ALS-XY-WING Exemple.png"><br><br>
<br><br><img src="images/Aide/Jellyfishs.png"><br><br>
<br><br><img src="images/Aide/squirmbag.png"><br><br>
<br><br><img src="images/Aide/3D Medusa sees two different colors.png"><br><br>
<br><br><img src="images/Aide/3D Medusa two colors in a cell.png"><br><br>
<br><br><img src="images/Aide/Nishio.png"><br><br>
<br><br><img src="images/Aide/Y-Wing.png"><br><br>
<br><br><img src="images/Aide/Y-Wing 1.png"><br><br>
<br><br><img src="images/Aide/ALS-Chain 1.png"><br><br>
<br><br><img src="images/Aide/ALS-Chain 2.png"><br><br>
<br><br><img src="images/Aide/ALS-Chain continu exemple 2.png"><br><br>
<br><br><img src="images/Aide/ALS-Chain continu exemple.png"><br><br>
<br><br><img src="images/Aide/ALS-Chain discontinu exemple.png"><br><br>
<br><br><img src="images/Aide/ALS-Chain Exemple1.png"><br><br>
<br><br><img src="images/Aide/ALS-Chain exemple page 23.png"><br><br>
<br><br><img src="images/Aide/ALS-Chain1.png"><br><br>

